# Generated by Django 3.1 on 2020-08-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_images', '0001_initial'),
        ('users', '0002_auto_20200808_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profile_images.profileimage'),
        ),
    ]
