# Generated by Django 3.1 on 2020-08-10 03:17

from django.db import migrations, models
import profile_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_images/default_profile_image.jpg', upload_to=profile_images.models.get_upload_path, verbose_name='profile image')),
            ],
        ),
    ]
